---
engines:
  csslint:
    enabled: false
  duplication:
    enabled: false
    config:
      languages:
      - ruby
      - javascript
      - python
      - php
  eslint:
    enabled: true
    channel: "eslint-3"
    config:
      config: .eslintrc.js
  fixme:
    enabled: false
ratings:
  paths:
  - "**.css"
  - "**.inc"
  - "**.js"
  - "**.jsx"
  - "**.module"
  - "**.php"
  - "**.py"
  - "**.rb"
exclude_paths: []
